version: '3.4'  

services:
  front:
    image: emptyup-front
    container_name: emptyup-front
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    restart: always
    ports:      
      - 3000:80
  back:
    image: emptyup-back
    container_name: emptyup-back
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    restart: always
    environment:
      - EMUP_HOST: db
      - EMUP_DB: "empty_up_db"
      - EMUP_PASSWORD: "K}63z-4NraxU~8"
    ports:
      - 3001:3000

  db:
   image: postgres
   container_name: emptyup-db
   restart: always
   environment:
      POSTGRES_DB: empty_up_db
      POSTGRES_USER: empty_up_db_admin
      POSTGRES_PASSWORD: K}63z-4NraxU~8
   volumes:
    - ./docker/db/db-dump/schemaDb.sql:/docker-entrypoint-initdb.d/create_tables.sql                                                                          
