version: '3.3'

services:
  front:
    image: emptyup-front
    container_name: emptyup-front
    build:
      dockerfile: ./docker/front/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
    - ./client:/var/www/emptyup
    - /var/www/emptyup/node_modules
  back:
    image: emptyup-back
    container_name: emptyup-back
    build:
      dockerfile: ./docker/back/Dockerfile
    restart: always
    ports:
      - 3001:3000
    volumes:
    - ./server:/var/www/emptyup
    - /var/www/emptyup/node_modules
    - ./docker/back/.env:/var/www/emptyup/.env

  db:
   image: postgres
   container_name: emptyup-db
   restart: always
   environment:
    POSTGRES_DB: postgres
    POSTGRES_USER: empty_up_db_admin
    POSTGRES_PASSWORD: K}63z-4NraxU~8
   ports:
      - 5432:5432
   volumes:
    - ./docker/db/db-dump/:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: empty_up@gmail.com
      PGADMIN_DEFAULT_PASSWORD: K}63z-4NraxU~8
    ports:
      - "5050:5050"